name: {{ cookiecutter.package_name }}
channels:
  - defaults
  - conda-forge
dependencies:
  - python={{ cookiecutter.python_version }}
  # Core dependencies
  {%- if cookiecutter.use_gymnasium == 'y' %}
  - gymnasium
  {%- endif %}
  {%- if cookiecutter.use_minigrid == 'y' %}
  - minigrid
  {%- endif %}
  {%- if cookiecutter.use_pytorch == 'y' %}
  - pytorch
  - cudatoolkit
  {%- endif %}
  {%- if cookiecutter.use_pytorch_lightning == 'y' %}
  - pip:
    - pytorch-lightning
  {%- endif %}
  {%- if cookiecutter.use_tensorflow == 'y' %}
  - tensorflow
  {%- endif %}
  {%- if cookiecutter.use_stable_baselines3 == 'y' %}
  - pip:
    - stable-baselines3
  {%- endif %}
  {%- if cookiecutter.use_ray == 'y' %}
  - ray
  {%- endif %}
  {%- if cookiecutter.use_wandb == 'y' %}
  - wandb
  {%- endif %}
  
  # Utilities
  - notebook
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - pandas
  - tqdm
  - hydra-core
